# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunModularityClusteringCpp <- function(SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename) {
    .Call(`_gficf_RunModularityClusteringCpp`, SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename)
}

jaccard_coeff <- function(idx, printOutput) {
    .Call(`_gficf_jaccard_coeff`, idx, printOutput)
}

non0LogColLmS <- function(sY, X, ldepth, maxCells = 0L, ncores = 1L) {
    .Call(`_gficf_non0LogColLmS`, sY, X, ldepth, maxCells, ncores)
}

colMeanVarS <- function(sY, rowSel, ncores = 1L) {
    .Call(`_gficf_colMeanVarS`, sY, rowSel, ncores)
}

colSumByFac <- function(sY, rowSel) {
    .Call(`_gficf_colSumByFac`, sY, rowSel)
}

inplaceColMult <- function(sY, mult, rowSel, ncores = 1L) {
    .Call(`_gficf_inplaceColMult`, sY, mult, rowSel, ncores)
}

inplaceWinsorizeSparseCols <- function(sY, n, ncores = 1L) {
    .Call(`_gficf_inplaceWinsorizeSparseCols`, sY, n, ncores)
}

jsDist <- function(m, ncores = 1L) {
    .Call(`_gficf_jsDist`, m, ncores)
}

orderColumnRows <- function(p, i) {
    .Call(`_gficf_orderColumnRows`, p, i)
}

smatColVecCorr <- function(sY, sv, parallel = TRUE) {
    .Call(`_gficf_smatColVecCorr`, sY, sv, parallel)
}

arma_mat_cor <- function(m) {
    .Call(`_gficf_arma_mat_cor`, m)
}

rcpp_WMU_test <- function(M, idx1, idx2) {
    .Call(`_gficf_rcpp_WMU_test`, M, idx1, idx2)
}

rcpp_parallel_jaccard_coef <- function(mat, printOutput) {
    .Call(`_gficf_rcpp_parallel_jaccard_coef`, mat, printOutput)
}

rcpp_parallel_WMU_test <- function(matX, matY, printOutput) {
    .Call(`_gficf_rcpp_parallel_WMU_test`, matX, matY, printOutput)
}

